language: ruby
rvm:
- 2.2.2
before_install: gem install bundler -v 1.11.2
deploy:
  provider: rubygems
  api_key:
    secure: CjKZEk2TI18/mrYBlMY2GSlLdI6oNUVDjlJkjwAWUeLUBK8k34BZLejoC8VsCle1PQzeXgialUJuzKhMEHRYrMWhh+jYPBcNfrI+rWF2vYRohWt77eKG6aEL/Gb3sc8V2xY7By5lPx7vNkqDpjbz+i0Hv0AXO5uApXGOzl74dII/L6GC1kykzr8Fjlqrs7UX63uY4q88N1YqhpLIzl/OmZpSogXEAIdcVmZy/kNAw8hstcVCjRoPGZjNd5eb+ojxMhcBAK+3xlh8tHOIRxygGDf810Flik/DhZjjRIb9KLraWS4Wy2qz93vWFfqdY0cO53y6BLdM1dZdzGqjI2ATJnruF4PbLTg+evys32LaLes+bKhn+3upjM/DzyfcNMpFd0+pOgweuC2pfhSACzDmxbZiUNcDE9ZUY0/vogm2/zI6eDi8uTMI1XIEPdl3lOmfmsEG8gR3DDCUQqpQNkZYRSW7L5svgwdx8z3cfaTiOVC3pQ5sDny0nenN91BsHB0pMuRKp637tDpQYPOMyDUHkBGPlNcWAm1fBFQZlqFanmoabu1iiRRL8kVWpkgajwt0aA/lIR3utQ/NIWDkhpPnJ3w5DhIC/vryKktzbo/YLO361ZFiRImzOhM8Pg5A/KKU5deJdnWRhknYQwJ1/1OaSl8jMO9tsBzxfGxjaKeAA8c=
  gem: sanitize_order
  on:
    tags: true
    repo: westfieldlabs/sanitize_order
