language: ruby
rvm:
- 2.2.2
before_install: gem install bundler -v 1.11.2
deploy:
  provider: rubygems
  api_key:
    secure: kzQt0xAjLrPpOvmiIgbhXI0aj9uU0WVJONC6tyYoikftrPku++E0JO64SryFZWTtI2ffGh3yhg484EjWSNm4Go78DWhYyMAbYVYM1Vee0ifUyRysrtxvMWCEhbE/7nzXXCsUNnRISzpLxP81TszCxEoG6eTSwjbMiDvLg79qKR3psxVorcSXaNwDOr5Oz8usNpubVFO7DyHWEZ7RsrJ76dLzocMdSxcjRD3MCkKJL/ugh+oX/4t8QwNCCO/EKuThIHWDkFAoSrPuLzMSRnYVVyO5QWg3W4kLYcPj3hPIj7zMEjbbwc9EUnc0trm7PEI9A/0pgJvkCDKpcVVgWuH/g6m9NuJ+enwZaUpg5f0zRIdkDdHiyRxtsiPDpE4d/wZSk/QRSYtxHgrQbfFxnWAFA42oMXzvWUMCs+pbIqkcuQzllp/DrtDyirWFwu0LE95baDdGuMLekN77cX9uOK6vOYDF3AQgYHGW7+0p3mnBQINn84ffhG8r5TuQLays8TFtKuTfigyU4BRIF6IJFr+YY/N93938gLmegfIGYmX34EHtVmN82H0Ih0oGuFL+05ttuv4op3QhnQK/3Vtop93xGs/0GuiQHg1S3kArs9bMs8dq/TZOB11MlEmQA08xMnbg38z3g4ioT0mdXsfncx+yJXyN70tM81U38g9KDdxihoA=
  gem: sanitize_order
  on:
    tags: true
    repo: westfieldlabs/sanitize_order
